version: '2'

services:

  ################
  ## MYSQL DATA ##
  ################

  kac-mysql-data:
    command: '/bin/bash'
    container_name: 'kac-mysql-data'
    image: 'arungupta/mysql-data-container'

  ################
  ## REDIS DATA ##
  ################

  kac-redis-data:
    build:
      context: .
      dockerfile: ./docker/build-redis-data/Dockerfile
    container_name: 'kac-redis-data'
    image: 'kenoantigen/kac-redis-data'
    volumes:
      - '/data'

  ##################
  ## MYSQL SERVER ##
  ##################

  kac-mysql-server:
    container_name: 'kac-mysql-server'
    depends_on:
      - 'kac-mysql-data'
    environment:
      - 'MYSQL_ROOT_PASSWORD=secret'
    image: 'mysql:5.5'
    volumes_from:
      - 'kac-mysql-data'

  ###########
  ## REDIS ##
  ###########

  kac-redis:
    container_name: 'kac-redis'
    image: redis
    depends_on:
      - 'kac-redis-data'
    volumes_from:
      - 'kac-redis-data'
    command: 'redis-server --appendonly yes'

  kac-redis-cli:
    container_name: 'kac-redis-cli'
    image: redis
    depends_on:
      - 'kac-redis-data'
    volumes_from:
      - 'kac-redis-data'
    command: 'redis-cli'


  ############
  ## CLIENT ##
  ############

  kac-client:
    build:
      context: .
      dockerfile: ./docker/build-client/Dockerfile
    command: '/bin/bash'
    command: '/bin/bash'
    container_name: 'kac-client'
    depends_on:
      - 'kac-mysql-server'
      - 'kac-redis'
    image: 'kenoantigen/kac-client'
    volumes:
      - ./bin:/home/keno/kac-client/bin
      - ./docs:/home/keno/kac-client/docs
      - ./etc:/home/keno/kac-client/etc
      - ./log:/home/keno/kac-client/log
      - ./lib:/home/keno/kac-client/lib
      - ./t:/home/keno/kac-client/t
      - ./var:/home/keno/kac-client/var

